import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import axios from 'axios';

export default function Home() {

  const clickHandler = () => {
    console.log('押下した。');

    axios.get('http://localhost:8080/test1').then(res => {
      console.log('結果：', res)
    })
  }

  const registerUser = () => {
    console.log('押下した。');

    axios.post('http://localhost:8080/api/v1/user').then(res => {
      console.log('結果：', res)
    })
  }

  const registerTemporaryUser = () => {
    console.log('押下した。');

    axios.post('http://localhost:8080/api/v1/temporary_user').then(res => {
      console.log('結果：', res)
    })
  }

  
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1>Prague itinerary</h1>
        <button onClick={() => clickHandler()}>ボタン</button>
        <button onClick={() => registerUser()}>ユーザー登録ボタン</button>
        <button onClick={() => registerTemporaryUser()}>仮ユーザー登録ボタン</button>
      </main>
    </>
  )
}
